"""Abstract contracts and results schemas for strategy validation engines."""

from __future__ import annotations

import abc
from typing import TYPE_CHECKING, Any
from pydantic import BaseModel, Field

if TYPE_CHECKING:
    import pandas as pd
    from research.strategies.models import Strategy


class ValidationResult(BaseModel):
    """Output details generated by strategy validation checks."""

    passed: bool = Field(..., description="True if validation criteria were satisfied")
    metrics: dict[str, float] = Field(default_factory=dict, description="Calculated statistics")
    details: dict[str, Any] = Field(
        default_factory=dict, description="Diagnostic data (splits, parameter values)"
    )

    model_config = {"frozen": True}


class IValidator(abc.ABC):
    """Abstract contract for specifying a strategy validation check (e.g. out-of-sample)."""

    @property
    @abc.abstractmethod
    def name(self) -> str:
        """Name of validation routine (e.g. 'Walk-forward Validation')."""

    @abc.abstractmethod
    def validate(self, strategy: Strategy, data: pd.DataFrame) -> ValidationResult:
        """Execute validation algorithm against target strategy rules using historical data."""
