"""Immutable Pydantic models for the Order Management System (OMS).
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field


class OrderRequest(BaseModel):
    """An incoming request to create a new order."""

    order_id: str
    symbol: str
    direction: str  # BUY, SELL
    quantity: float
    order_type: str  # MARKET, LIMIT
    price: float = 0.0
    time_in_force: str = "GTC"
    strategy_id: str = ""

    model_config = ConfigDict(frozen=True)


class Order(BaseModel):
    """An execution order entry managed by the OMS."""

    order_id: str
    strategy_id: str = ""
    symbol: str = ""
    quantity: float = 0.0
    price: float = 0.0
    order_type: str = "LIMIT"  # MARKET, LIMIT
    side: str = "BUY"  # BUY, SELL
    status: str = "NEW"  # NEW, VALIDATED, QUEUED, ROUTED, PARTIALLY_FILLED, FILLED, CANCELLED, REJECTED, EXPIRED
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    executed_price: Optional[float] = None
    executed_quantity: float = 0.0
    parent_id: Optional[str] = None
    target_broker: Optional[str] = None

    # Compatibility properties/fields for state machine / orchestrator
    request: Optional[OrderRequest] = None
    filled_quantity: float = 0.0
    avg_price: float = 0.0
    created_time: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    model_config = ConfigDict(frozen=True)


class ExecutionReport(BaseModel):
    """An execution status update generated by execution adapters."""

    execution_id: str
    order_id: str
    status: str
    price: float
    quantity: float
    commission: float = 0.0
    error_message: Optional[str] = None
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    model_config = ConfigDict(frozen=True)


class Fill(BaseModel):
    """A partial or complete order fill execution transaction."""

    fill_id: str
    order_id: str
    price: float
    quantity: float
    commission: float = 0.0
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    model_config = ConfigDict(frozen=True)


class OrderState(BaseModel):
    """Current order state and state transit logs."""

    order: Order
    history: List[str] = Field(default_factory=list)
    last_updated: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    model_config = ConfigDict(frozen=True)


class OrderBook(BaseModel):
    """Order book bids and asks limits levels."""

    symbol: str
    bids: List[tuple[float, float]] = Field(default_factory=list)  # (price, quantity)
    asks: List[tuple[float, float]] = Field(default_factory=list)

    model_config = ConfigDict(frozen=True)


class OrderHistory(BaseModel):
    """Full lifecycle tracking history of an order."""

    order_id: str
    states: List[OrderState] = Field(default_factory=list)

    model_config = ConfigDict(frozen=True)


class OrderAudit(BaseModel):
    """Audit logs for order status changes."""

    audit_id: str
    order_id: str
    previous_status: str
    new_status: str
    message: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    model_config = ConfigDict(frozen=True)


class ParentOrder(BaseModel):
    """Parent order wrapper managing algorithmic slicing."""

    parent_id: str
    order: Order
    algo_type: str
    algo_params: Dict[str, Any] = Field(default_factory=dict)
    child_ids: List[str] = Field(default_factory=list)

    model_config = ConfigDict(frozen=True)


class ChildOrder(BaseModel):
    """Sliced child order details."""

    child_id: str
    parent_id: str
    order: Order
    sequence_num: int

    model_config = ConfigDict(frozen=True)


class OrderExecutionPlan(BaseModel):
    """Pre-calculated execution times and quantities for sliced orders."""

    plan_id: str
    parent_id: str
    total_quantity: float
    slices_count: int
    interval_seconds: int
    scheduled_times: List[datetime]

    model_config = ConfigDict(frozen=True)


class ExecutionInstruction(BaseModel):
    """Execution adapter target instructions."""

    route_id: str
    destination: str
    display_type: str

    model_config = ConfigDict(frozen=True)


class RouteDecision(BaseModel):
    """Routing choice determined by the RoutingEngine."""

    decision_id: str
    order_id: str
    target_exchange: str
    instruction: ExecutionInstruction

    model_config = ConfigDict(frozen=True)
