"""Pydantic schemas for quantitative research papers generated by experiments."""

from __future__ import annotations

from datetime import datetime, timezone
from pydantic import BaseModel, Field


class ResearchPaper(BaseModel):
    """Canonical model for a structured quantitative Research Paper."""

    paper_id: str = Field(..., description="Unique paper identifier")
    experiment_id: str = Field(..., description="Associated research experiment ID")
    title: str = Field(...)
    abstract: str = Field(..., description="Brief overview of research findings")
    hypothesis: str = Field(..., description="The theoretical edge or quantitative claim")
    methodology: str = Field(..., description="Step-by-step math and logic process")
    dataset: str = Field(..., description="Dataset configuration summary")
    features: list[str] = Field(default_factory=list, description="List of feature store inputs used")
    statistics: dict[str, float] = Field(
        default_factory=dict, description="Calculated statistics (e.g. t-stat, p-value)"
    )
    results: dict[str, float] = Field(
        default_factory=dict, description="Performance metrics (Sharpe, profit factor)"
    )
    weaknesses: list[str] = Field(default_factory=list, description="Identified limitations of model")
    future_work: list[str] = Field(default_factory=list, description="Future iterations and extensions")
    lessons_learned: list[str] = Field(default_factory=list, description="Key takeaways and conclusions")
    published_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    model_config = {"frozen": True}
