"""Strategy Factory models tracking candidates and evaluations.
"""

from __future__ import annotations
from typing import Dict, Any, List, Optional
from pydantic import BaseModel, ConfigDict

class StrategyCandidate(BaseModel):
    """Represents a generated candidate strategy structure."""
    name: str
    rules: Dict[str, Any]

    model_config = ConfigDict(frozen=True)

class StrategyScore(BaseModel):
    """Scores cards generated by the evaluator."""
    profit_factor: float
    sharpe: float
    drawdown: float
    score: float

    model_config = ConfigDict(frozen=True)
