"""Market state definitions."""

from __future__ import annotations

# Explicit states definitions
TRENDING_UP = "TRENDING_UP"
TRENDING_DOWN = "TRENDING_DOWN"
RANGING = "RANGING"
HIGH_VOLATILITY = "HIGH_VOLATILITY"
LOW_LIQUIDITY = "LOW_LIQUIDITY"
UNUSUAL_VOLUME = "UNUSUAL_VOLUME"
DATA_STALE = "DATA_STALE"
HEALTHY = "HEALTHY"
UNHEALTHY = "UNHEALTHY"
