"""Unit tests for the KnowledgeReportGenerator reports compiler."""

from __future__ import annotations

import pytest

from knowledge.reports.generator import KnowledgeReportGenerator
from knowledge.models import Rule, Belief, Evidence, SourceReference, KnowledgeStatus
from knowledge.contradictions.detector import InvestigationTask


def test_reports_structures():
    """Verify dictionary fields generated by KnowledgeReportGenerator."""
    rule = Rule(
        rule_id="r-1",
        name="Rule A",
        rule_type="risk",
        expression="vol > 20",
        evidence_ids=["ev-1"],
        status=KnowledgeStatus.ACTIVE
    )
    
    belief = Belief(
        belief_id="b-1",
        claim="Bullish",
        confidence=0.8,
        evidence_ids=["ev-1"]
    )
    
    ref = SourceReference(ref_type="experiment", ref_id="exp-1", description="desc")
    evidence = Evidence(
        evidence_id="ev-1",
        source=ref,
        metric_name="sharpe",
        metric_value=1.5
    )
    
    task = InvestigationTask(
        task_id="t-1",
        contradiction_type="rule_conflict",
        description="Duplicate rule",
        offending_ids=["r-1"]
    )
    
    # 1. Knowledge Report
    rep_k = KnowledgeReportGenerator.generate_knowledge_report([rule], [belief], ["insight-1"])
    assert rep_k["report_type"] == "Knowledge Report"
    assert rep_k["summary"]["active_rules_count"] == 1
    assert rep_k["summary"]["active_beliefs_count"] == 1
    
    # 2. Belief Report
    rep_b = KnowledgeReportGenerator.generate_belief_report([belief])
    assert rep_b["report_type"] == "Belief Report"
    assert rep_b["metrics"]["active_beliefs"] == 1
    assert rep_b["metrics"]["average_confidence"] == 0.8
    
    # 3. Rule Report
    rep_r = KnowledgeReportGenerator.generate_rule_report([rule])
    assert rep_r["report_type"] == "Rule Report"
    assert rep_r["metrics"]["total_rules"] == 1
    assert rep_r["metrics"]["rules_by_category"]["risk"] == 1
    
    # 4. Evidence Report
    rep_e = KnowledgeReportGenerator.generate_evidence_report([evidence])
    assert rep_e["report_type"] == "Evidence Report"
    assert rep_e["metrics"]["total_evidence_entries"] == 1
    assert rep_e["metrics"]["evidence_by_source_type"]["experiment"] == 1
    
    # 5. Contradiction Report
    rep_c = KnowledgeReportGenerator.generate_contradiction_report([task])
    assert rep_c["report_type"] == "Contradiction Report"
    assert rep_c["metrics"]["total_active_contradictions"] == 1
    assert rep_c["metrics"]["contradictions_by_type"]["rule_conflict"] == 1
