"""Pydantic schemas for rule-based Strategy definitions generated by research."""

from __future__ import annotations

from typing import Any
from pydantic import BaseModel, Field


class BaseRule(BaseModel):
    """Common structure for all trading strategy rules."""

    name: str = Field(..., description="Descriptive name of rule")
    condition_expr: str = Field(..., description="Mathematical or logical conditional string")
    parameters: dict[str, Any] = Field(default_factory=dict, description="Configuration parameters")

    model_config = {"frozen": True}


class EntryRule(BaseRule):
    """Rule defining trade execution entry triggers."""


class ExitRule(BaseRule):
    """Rule defining trade execution exit triggers."""


class RiskRule(BaseRule):
    """Rule defining trailing stop-loss, take-profit, or max-drawdown boundaries."""


class PositionSizingRule(BaseRule):
    """Rule defining quantity sizing calculation logic (e.g. Kelly criterion, fixed risk)."""


class MarketFilter(BaseRule):
    """Rule defining general environment states under which strategy runs (e.g. regime filters)."""


class Strategy(BaseModel):
    """Canonical model for a versioned research-backed Strategy."""

    strategy_id: str = Field(...)
    name: str = Field(...)
    version: str = Field(default="1.0.0")
    experiment_id: str = Field(..., description="Reference ID to the research experiment that produced it")
    entry_rules: list[EntryRule] = Field(default_factory=list)
    exit_rules: list[ExitRule] = Field(default_factory=list)
    risk_rules: list[RiskRule] = Field(default_factory=list)
    position_sizing_rules: list[PositionSizingRule] = Field(default_factory=list)
    market_filters: list[MarketFilter] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)

    model_config = {"frozen": True}
