"""AI Signal Engine models."""

from __future__ import annotations

from typing import Optional
from pydantic import BaseModel


class AISignalResult(BaseModel):
    """Output generated by the AI Signal Engine."""
    symbol: str
    signal: str  # "BUY", "SELL", "WAIT"
    entry_price: float
    stop_loss: float
    take_profit: float
    risk_reward: float
    confidence: float  # 0.0 to 1.0
    expected_win_rate: float  # 0.0 to 1.0
    reasoning: str
