"""Immutable Pydantic models for the Research Intelligence Engine.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field


class HypothesisStatus(str, Enum):
    PENDING = "PENDING"
    VALIDATED = "VALIDATED"
    REJECTED = "REJECTED"


class ResearchHypothesis(BaseModel):
    """A research hypothesis outlining parameters and target expectations."""

    hypothesis_id: str
    description: str
    symbol: str
    parameters: Dict[str, Any] = Field(default_factory=dict)
    status: HypothesisStatus = HypothesisStatus.PENDING
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    model_config = ConfigDict(frozen=True)


class ResearchScore(BaseModel):
    """Grading score card for a completed experiment/hypothesis run."""

    hypothesis_id: str
    sharpe: float
    drawdown: float
    win_rate: float
    parameter_stability: float
    quality_score: float  # Final score out of 10
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    model_config = ConfigDict(frozen=True)


class ResearchRank(BaseModel):
    """Ranking results of tested hypotheses."""

    ranking_id: str
    ranked_hypothesis_ids: List[str]
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    model_config = ConfigDict(frozen=True)


class ExperimentRecommendation(BaseModel):
    """Advisory parameter changes generated by reviewing experiments."""

    recommendation_id: str
    hypothesis_id: str
    actionable_parameter_changes: Dict[str, Any]
    rationale: str
    confidence: float
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    model_config = ConfigDict(frozen=True)
